name: auto-format
on: 
  pull_request:
    branches: [main]

env: # environment variables (available in any part of the action)
  NODE_VERSION: 12

jobs:
  format:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Install Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: prettier
        run: yarn prettier --write './'
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: 
          echo "github_token- ${{secrets.GITHUB_TOKEN}}" &&
          git config user.email "your_friendly_github_formatter@wonderschool.noreply.com" &&
          git config user.name "your friendly github PR formatter" &&
          git commit -am "Automated linting" &&
          git push
        # with: 
        #   repo-token: ${{ secrets.GITHUB_TOKEN }}

          # git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git &&
          